DROP TABLE IF EXISTS users, films, friends, likes, genres, film_genres, mpa ;

CREATE TABLE IF NOT EXISTS users (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  login varchar(50) NOT NULL,
  name varchar(50),
  email varchar(50) NOT NULL UNIQUE,
  birthday date
);

CREATE TABLE IF NOT EXISTS friends (
  following_user_id bigint REFERENCES users(user_id),
  followed_user_id bigint REFERENCES users(user_id),
  PRIMARY KEY (following_user_id, followed_user_id)
);

CREATE TABLE IF NOT EXISTS mpa (
  mpa_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  mpa_name varchar(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
  film_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name varchar(50) NOT NULL,
  description varchar(200),
  releaseDate date,
  duration integer,
  mpa integer REFERENCES mpa(mpa_id)
);

CREATE TABLE IF NOT EXISTS likes (
  film_id bigint REFERENCES films(film_id),
  user_id bigint REFERENCES users(user_id),
  created timestamp,
  PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS genres (
  genre_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  genre_name varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id bigint REFERENCES films(film_id),
  genre_id integer REFERENCES genres(genre_id),
  last_update timestamp,
  PRIMARY KEY (film_id, genre_id)
);

